idumi28/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from members.views import login_user,logout_user,register_user

app_name = 'main'

urlpatterns = [
    path('' , views.Home, name='homePage'),
    path("News/detail/<slug:slug>", views.News_detail, name="newDetail"),
    path("News/", views.NewsPage, name="News"),
    # path("Search", views.searchbar, name="search"),
    path('about/', views.About , name='about'),
    path("only_us/", views.Elements, name="elements"),
    path("courses/", views.Courses, name="courses"),
    path("contact/", views.Contact, name="Contact"),
    path("achivments/", views.Achivments, name="achivments"),
    path("achivments/<slug:slug>", views.AchivmentsDetail, name="achivmentsDetail"),
    path("login/", login_user, name="login"),
    path("logout/",logout_user, name="logout"),
    path("registration/", register_user , name="register"),
    path("teachers/<slug:slug>", views.TeachersDetail, name="teacherProfile"),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <div class="banner_content text-center">
              <h2>Biz haqimizda</h2>
              <div class="page_link">
                <a href="{% url 'main:homePage' %}">bosh sahifa</a>
                <a href="">Biz haqimizda</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ================End Home Banner Area ================= -->

  <!-- ================ Start About Area ================= -->
  <section class="about_area section_gap">
    <div class="container">
      <div class="row h_blog_item">
        <div class="col-lg-6">
          <div class="h_blog_img">
            <img class="img-fluid" src="{% static 'img/banner/28idumi.jpg' %}" alt="" />
          </div>
        </div>
        <div class="col-lg-6">
          <div class="h_blog_text">
            <div class="h_blog_text_inner left right">
              <h4>Bizning maktabga hush kelibsiz</h4>
              <p>Biz bu websaytimizda bizning makatabimiz hayoti haqida , maktabimiz yangiliklari , yutuqlari haqida batafsil ma'lumot beramiz</p>
              <p>Bu sahifamizda esa o'zimizning ustozlar , rahbarlar hamda o'zimizning qoidalar haqida batafsil ma'lumot beramiz</p>
              <p>To'liqroq malumot olish uchun pastdagi tugmani bosing.</p>
              <a class="primary-btn" href="{% url 'main:elements' %}">Learn More <i class="ti-arrow-right ml-1"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ================ End About Area ================= -->

  <!-- ================ Start Feature Area ================= -->
  <section class="feature_area section_gap_top title-bg">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-5">
          <div class="main_title">
            <h2 class="mb-3 text-white">Awesome Feature</h2>
            <p>Replenish man have thing gathering lights yielding shall you</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 col-md-6">
          <div class="single_feature">
            <div class="icon">
              <span class="flaticon-student"></span>
            </div>
            <div class="desc">
              <h4 class="mt-3 mb-2">Scholarship Facility</h4>
              <p>Bizning o'quvchilarimizning har biri , har yili oliygohlarga kirishmoqda</p>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6">
          <div class="single_feature">
            <div class="icon">
              <span class="flaticon-book"></span>
            </div>
            <div class="desc">
              <h4 class="mt-3 mb-2">Maktabimiz Fanlari</h4>
              <p>BIzning maktab-internatimiz matematika va Ingliz tili fanlariga ixtisoslashtirilgan</p>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6">
          <div class="single_feature">
            <div class="icon">
              <span class="flaticon-earth"></span>
            </div>
            <div class="desc">
              <h4 class="mt-3 mb-2">Global Sertifikatlar</h4>
              <p>Ko‘plab o‘quvchilarimiz turli sertifikatlarga ega bo‘lmoqda</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ================ End Feature Area ================= -->

  <!-- ================ Start Testimonial Area ================= -->
  <div class="testimonial_area section_gap">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-5">
          <div class="main_title">
            <h2 class="mb-3">BIzning maktab-internatimiz o'qituvchilari</h2>
            <p>Replenish man have thing gathering lights yielding shall you</p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="testi_slider owl-carousel">
          
          
          {% for teacher in teachers %}
          <a href="{% url 'main:teacherProfile' teacher.slug %}"  style="text-decoration: none;color: gray;">
          <div class="testi_item">
            <div class="row">
              <div class="col-lg-4 col-md-6">
                <img src="{{teacher.image.url}}" alt="" />
              </div>
              <div class="col-lg-8">
                <div class="testi_text">
                  <h4>{{teacher.fullname}}</h4>
                  <p>Him, made can't called over won't there on divide there male fish beast own his day third seed sixth seas unto. Saw from</p>
                </div>
              </div>
            </div>
          </div>
        </a>
          {% endfor %}
            

        </div>
      </div>
    </div>
  </div>
  <!-- ================ End Testimonial Area ================= -->

  <!-- ================ Start footer Area ================= -->
{% endblock %}

templates/achivments.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="icon" href="{% static 'img/logos2.png' %}" type="image/png" />
    <title>News</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" />
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}" />
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'scss/style.css' %}" />
  </head>

  <body>
    <!-- ================ Start Header Menu Area ================= -->
    <header class="header_area">
      <div class="main_menu">
        <div class="search_input" id="search_input_box">
          <div class="container">
            <form class="d-flex justify-content-between" method="" action="">
              <input type="text" class="form-control" id="search_input" placeholder="Search Here" />
              <button type="submit" class="btn"></button>
              <span class="ti-close" id="close_search" title="Close Search"></span>
            </form>
          </div>
        </div>
  
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand logo_h" href="{% url 'main:homePage' %}"><img src="{% static 'img/logos1.png' %}" style="width: 120px;" alt="" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="icon-bar"></span> <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
              <ul class="nav navbar-nav menu_nav m-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:homePage' %}">Bosh menu</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:about' %}">Biz haqimizda</a>
                </li>
                <li class="nav-item submenu dropdown">
                  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">sahifalar</a>
                  <ul class="dropdown-menu">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'main:courses' %}">Maktabimiz kurslari</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'main:elements' %}">Elements</a>
                    </li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:achivments' %}">Yutuqlarimiz</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:News' %}">Yangiliklar</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:Contact' %}">Bog'lanish</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="http://127.0.0.1:8000/" target="_blank">Kutubxona</a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link search" id="search"><i class="ti-search"></i></a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:login' %}">Login</a>
                </li>
                   <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:register' %}">Register</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!-- ================ End Header Menu Area ================= -->
  
    <!-- ================ Start Home Banner Area ================= -->
    <section class="home_banner_area">
      <div class="banner_inner">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              
                <br>
              
              <div class="banner_content text-center">
                <p class="text-uppercase">Oltinko'l tumani</p>
                <h2 class="text-uppercase mt-4 mb-3">28-Davlat iqtisoslashgan maktab internatining</h2>
                <p class="text-uppercase">Yutuqlarimiz</p>
                <div>
                  <a href="{% url 'main:about' %}" class="primary-btn2 mb-3 mb-sm-0">Biz haqimizda</a>
                  <a href="{% url 'main:achivments' %}" class="primary-btn ml-sm-3 ml-0">Yutuqlarimiz</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ================ End Home Banner Area ================= -->

    <!-- ================Blog Area ================= -->
    <section class="blog_area section_gap">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                  <div class="blog_left_sidebar">
                      {% for new in achives %}
                      <article class="row blog_item">
                          <div class="col-md-12">
                              <div class="row">
                                  <div class="col-sm-12 col-md-4">
                                      <img src="{{ new.image.url }}" style="height: 400px; object-fit: contain;" alt="" />
                                  </div>
                                  <div class="blog_details col-sm-12 col-md-8">
                                      <a href="{% url 'main:achivmentsDetail' new.slug %}">
                                          <h2>{{ new.name }}</h2>
                                      </a>
                                      <p>{{ new.body|truncatewords:50 }}</p>
                                      <a href="{% url 'main:achivmentsDetail' new.slug %}" class="blog_btn">View More</a>
                                  </div>
                              </div>
                          </div>
                      </article>
                      {% endfor %}
  
                      <!-- Pagination -->
                      <nav aria-label="Page navigation example">
                          <ul class="pagination justify-content-center">
                              {% if achives.has_previous %}
                              <li class="page-item">
                                  <a class="page-link" href="?page={{ achives.previous_page_number }}" aria-label="Previous">
                                      <span aria-hidden="true">&laquo;</span>
                                  </a>
                              </li>
                              {% endif %}
  
                              {% for num in achives.paginator.page_range %}
                              <li class="page-item {% if achives.number == num %}active{% endif %}">
                                  <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                              </li>
                              {% endfor %}
  
                              {% if achives.has_next %}
                              <li class="page-item">
                                  <a class="page-link" href="?page={{ achives.next_page_number }}" aria-label="Next">
                                      <span aria-hidden="true">&raquo;</span>
                                  </a>
                              </li>
                              {% endif %}
                          </ul>
                      </nav>
  
                  </div>
              </div>
          </div>
      </div>
  </section>
  
    <!-- ================Blog Area ================= -->

    <!-- ================ Start footer Area ================= -->
    <footer class="footer-area section_gap text-white text-center text-lg-start text-muted">
      <section class="">
        <div class="container text-center text-white text-md-start mt-5">
          <!-- Grid row -->
          <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
              <!-- Content -->
              <h6 class="text-uppercase text-white fw-bold mb-4">
                <img src="{% static 'img/logos2.png' %}" style="width: 200px; object-fit: contain;" alt="">
              </h6>
              <p>
                Oltinko'l tumani 28-Davlat iqtisoslashgan maktab-internati
              </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4 text-white">
                Biz haqimizda
              </h6>
              <p>
                <a href="{% url 'main:homePage' %}" class="text-reset">Barchasi</a>
              </p>
              <p>
                <a href="{% url 'main:about' %}" class="text-reset">Biz haqimizda</a>
              </p>
              <p>
                <a href="{% url 'main:elements' %}" class="text-reset">Malumotlar</a>
              </p>
              <p>
                <a href="{% url 'main:courses' %}" class="text-reset">Maktabimiz kurslari</a>
              </p>
    
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4 text-white">
                Maktab hayoti
              </h6>
              <p>
                <a href="{% url 'main:homePage' %}" class="text-reset">Barchasi</a>
              </p>
              <p>
                <a href="{% url 'main:News' %}" class="text-reset">Yangiliklar</a>
              </p>
              <p>
                <a href="{% url 'main:achivments' %}" class="text-reset">Yutuqlarimiz</a>
              </p>
              <p>
                <a href="{% url 'main:Contact' %}" class="text-reset">Kontakt</a>
              </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4 text-white">Contact</h6>
              <p><i class="fas fa-home me-3"></i>Andijon shahar, O'zbekiston Oltinko'l tumani 28-IDUMI</p>
              <p>
                <i class="fas fa-envelope me-3"></i>
                info@example.com
              </p>
              <p><i class="fas fa-phone me-3"></i> + 998940270047</p>
              <p><i class="fas fa-print me-3"></i> + 998940270047</p>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row -->
        </div>
      </section>
      <!-- Section: Links  -->
    
      <!-- Copyright -->
      <!-- Copyright -->
    </footer>
    <div class="text-center p-4 bg-white" style="color: #002347;">
      © 2024 Copyright:
      <a class="text-reset fw-bold" href="https://t.me/umarovs_17">Website created by Umarov</a>
    </div>
    <!-- ================ End footer Area ================= -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/owl-carousel-thumb.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <!-- gmaps Js -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
    <script src="{% static 'js/gmaps.min.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
  </body>
</html>

templates/base.html
{% load static %}

<title>{% block title %}{% endblock title %}</title>

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="icon" href="{% static 'img/logos2.png' %}" type="" />
    <title>About Us</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" />
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}" />
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'scss/stylee.css' %}" />
  </head>

  <body>
    <!-- ================ Start Header Menu Area ================= -->
    <header class="header_area white-header">
      <div class="main_menu">
        <div class="search_input" id="search_input_box">
          <div class="container">
            <form class="d-flex justify-content-between" method="" action="">
              <input type="text" class="form-control" id="search_input" placeholder="Search Here" />
              <button type="submit" class="btn"></button>
              <span class="ti-close" id="close_search" title="Close Search"></span>
            </form>                                
          </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand" href="{% url 'main:homePage' %}"><img class="logo-2" src="{% static 'img/logos2.png' %}" style="width: 120px;" alt="" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="icon-bar"></span> <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
              <ul class="nav navbar-nav menu_nav m-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:homePage' %}">Bosh sahifa</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:about' %}">Biz haqimizda</a>
                </li>
                <li class="nav-item submenu dropdown">
                  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sahifalar</a>
                  <ul class="dropdown-menu">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'main:courses' %}">Maktabizmiz kurslari</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'main:elements' %}">Malumotlar</a>
                    </li>
                  </ul>
                </li>
                <li class="nav-item submenu">
                    <a class="nav-link" href="{% url 'main:News' %}">Yangiliklar</a>
                </li> 
                <li class="nav-item submenu">
                  <a class="nav-link" href="{% url 'main:achivments' %}">Yutuqlarimiz</a>
              </li> 
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:Contact' %}">Bog'lanish</a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link search py-4" id="search"><i class="ti-search"></i></a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:login' %}">Login</a>
                </li>
                   <li class="nav-item">
                  <a class="nav-link" href="{% url 'main:register' %}">Register</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>




{% block content %}
    
{% endblock content %}
    





<footer class="footer-area section_gap text-white text-center text-lg-start text-muted">
  <section class="">
    <div class="container text-center text-white text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase text-white fw-bold mb-4">
            <img src="{% static 'img/logos2.png' %}" style="width: 200px; object-fit: contain;" alt="">
          </h6>
          <p>
            Oltinko'l tumani 28-Davlat iqtisoslashgan maktab-internati
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4 text-white">
            Biz haqimizda
          </h6>
          <p>
            <a href="{% url 'main:homePage' %}" class="text-reset">Barchasi</a>
          </p>
          <p>
            <a href="{% url 'main:about' %}" class="text-reset">Biz haqimizda</a>
          </p>
          <p>
            <a href="{% url 'main:elements' %}" class="text-reset">Malumotlar</a>
          </p>
          <p>
            <a href="{% url 'main:courses' %}" class="text-reset">Maktabimiz kurslari</a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4 text-white">
            Maktab hayoti
          </h6>
          <p>
            <a href="{% url 'main:homePage' %}" class="text-reset">Barchasi</a>
          </p>
          <p>
            <a href="{% url 'main:News' %}" class="text-reset">Yangiliklar</a>
          </p>
          <p>
            <a href="{% url 'main:achivments' %}" class="text-reset">Yutuqlarimiz</a>
          </p>
          <p>
            <a href="{% url 'main:Contact' %}" class="text-reset">Kontakt</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4 text-white">Contact</h6>
          <p><i class="fas fa-home me-3"></i>Andijon shahar, O'zbekiston Oltinko'l tumani 28-IDUMI</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 998940270047</p>
          <p><i class="fas fa-print me-3"></i> + 998940270047</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <!-- Copyright -->
</footer>
<div class="text-center p-4 bg-white" style="color: #002347;">
  © 2024 Copyright:
  <a class="text-reset fw-bold" href="https://t.me/umarovs_17">Website created by Umarov</a>
</div>


      </footer>
      <!-- ================ End footer Area ================= -->
  
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'js/popper.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
      <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
      <script src="{% static 'js/owl-carousel-thumb.min.js' %}"></script>
      <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
      <script src="{% static 'js/mail-script.js' %}"></script>
      <!-- gmaps Js -->
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
      <script src="{% static 'js/gmaps.min.js' %}"></script>
      <script src="{% static 'js/theme.js' %}"></script>


    </body>
  </html>
  

templates/teachers.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <div class="banner_content text-center">
              <h2>O'qituvchi haqida</h2>
              <div class="page_link">
                <a href="{% url 'main:homePage' %}">bosh sahifa</a>
                <a href="">O'qituvchi haqida</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


<div class="container py-5">

  <div class="card mb-3">

    <div class="row g-0">

      <div class="col-md-4">
        <img src="{{teacher.image.url}}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        
        <div class="card-body">
          <center>
          <h2 class="justify-content-center align-items-center p-4">{{teacher.fullname}}</h2></center>
          <p class="card-text  p-3">{{teacher.bio}}</p>
          <p class="card-text p-3"><small class="text-body-secondary">
            fanlari:
            {% for subject in teacher.subjects.all %}
             {{subject}} ,
            {% endfor %}
                
          </small></p>
        </div>



      </div>

    </div>

  </div>



  <div class="row">
    
    {% for teacher in other_img %}
    <div class="col-sm-12 col-md-6 col-lg-4">

      <img src="{{teacher.image.url}}" class="img-fluid"  alt="">

    </div>
    {% endfor %}


  </div>


</div>


{% endblock content %}